name: Test automation WorkFlow

on:
    schedule:
    - cron: '00 18 * * *'
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running test automation framework
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false
    
    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test logs
        path: logs/
        
    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: screenshot
        path: screenshots/

    - name: Upload Test Reports as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: html-report
        path: report.html
        
    - name: Notify test sucess or failure
      if: always()
      run: echo "Test Execution Completed"

    - name: Copy Report to gh-pages folder
      if: always()

      run:
         mkdir -p public/extent-reports/
         cp -R report.html public/extent-reports/
         cp -R screenshots/ public/extent-reports/screenshots/
         ls -l

    - name:  Deploy
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4.7.3
      with:
        folder: public/extent-reports/
        token: ${{ secrets.meerapat }}
        clean: true
     
        



  
